name: example-environment
channels:
  - conda-forge
  - arcgispro-py3
dependencies:
  - python
  - numpy
  - esri
  - arcgis
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
