name: example-environment
channels:
  - conda-forge
  - esri
dependencies:
  - python
  - numpy
  - esri
  - arcgis
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - 
