name: example-environment
channels:
  - conda-forge
  - esri
dependencies:
  - python
  - numpy
  - arcgis
  - libgdal
  - pip:
    - sphinx-gallery
    - pandas
    - matplotlib
    - gdal
    - rtree
    - fiona
    - shapely
    - rasterio
    - geopandas
